FROM node:21-bullseye

WORKDIR /singh_harsimran_ui_garden/

# Copy package.json and package-lock.json
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm ci

# Install Playwright with Chromium
RUN npx playwright install --with-deps chromium

# Copy the rest of the project files
COPY . .

# Run the tests
CMD ["npm", "run", "ci:test"]
